apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-producer
  description: produces demo events
  labels:
    application: demo-app
  tags:
    - go
    - lambda
spec:
  type: service
  lifecycle: production
  owner: demo-team
  system: demo-system
  providesApis: 
    - demo-producer-api