apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-demo-component-producer
  description: deployment consumer
spec:
  type: github
  targets:
    - https://github.com/crivetechie/backstage-demo-component-producer/blob/main/catalog-info-component.yaml
    - https://github.com/crivetechie/backstage-demo-component-producer/blob/main/catalog-info-api.yaml