apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: backstage-demo-component-producer
  description: deployment consumer
spec:
  type: github
  targets:
    - ./catalog-info-component.yaml
    - ./catalog-info-api.yaml